### ISSUE TITLE
期待更多的示例或更加完善的文档 ~

### ISSUE THREAD

**Issue by cosven** [justdoit0823/pywxclient#11]
目前，很难知道这个库到底提供了哪些 API，光从 examples 中的两个例子来学习使用方法比较困难

既然这个库已经发了两个版本了， 作者能不能把文档给文档补充一下呐？

**Comment by justdoit0823** [comment]
@cosven please visit [pywxclient](http://pywxclient.readthedocs.io/en/latest/), this is a simple api document.
