### ISSUE TITLE
Client cannot run for newly registered accounts

### ISSUE THREAD

**Issue by nsorros** [justdoit0823/pywxclient#12]
Hi, I am trying to run your code and specifically the client example with a new wechat account I created and I receive this error which seems to be related to a new policy wechat introduced. Is there any way around that you are familiar with?

```For account security, newly registered WeChat accounts are unable to log in to Web WeChat. To use WeChat on a computer, use Windows WeChat or Mac WeChat at http://wechat.com```

**Comment by justdoit0823** [comment]
@nsorros This is the WeChat's official restriction. You can login with your mobile, and do some daily communications. After a period, you may try this again.
