### ISSUE TITLE
Can not login anymore

### ISSUE THREAD

**Issue by hippieZhou** [justdoit0823/pywxclient#16]
Hi，Developer, the repo of your maybe have some login issue,Do you have any plane to fix it?
<img width="1093" alt="Snipaste_2019-09-26_21-37-53" src="https://user-images.githubusercontent.com/13598361/65693072-421e8480-e0a6-11e9-92f6-4465a8dbdafb.png">

**Comment by justdoit0823** [comment]
The error message has told the truth.
