### ISSUE TITLE
windows 10 cant pip install 

### ISSUE THREAD

**Issue by francishero** [justdoit0823/pywxclient#2]
C:\Program Files\Python36\Scripts>pip3.6.exe install pywxclient
Collecting pywxclient
  Could not find a version that satisfies the requirement pywxclient (from versions: )
No matching distribution found for pywxclient

C:\Program Files\Python36\Scripts>pip.exe install pywxclient
Collecting pywxclient
  Could not find a version that satisfies the requirement pywxclient (from versions: )
No matching distribution found for pywxclient

**Comment by justdoit0823** [comment]
@francishero I am so sorry that I haven't upload this package to pypi. So you can't install with pip directly. But you can run command `pip install git+https://github.com/justdoit0823/pywxclient` to install it.
