### ISSUE TITLE
Cannot send a message (APIResponseError)

### ISSUE THREAD

**Issue by nvilcins** [justdoit0823/pywxclient#3]
I always get `APIResponseError` (without any details) when I try to send a message.

```
from pywxclient.core import Session, SyncClient, TextMessage

session = Session()
client = SyncClient(session)
client.get_authorize_url()
# open url and scan QR with phone
client.authorize()
client.login()

user_from = "@my_user_id"
user_to = "@friends_user_id"
msg = "test123"
tm = TextMessage(user_from, user_to, msg)

client.send_message(tm)
```

```
---------------------------------------------------------------------------
APIResponseError                          Traceback (most recent call last)
<ipython-input-3-952420276ad7> in <module>()
      3 msg = "test123"
      4 tm = TextMessage(user_from, user_to, msg)
----> 5 client.send_message(tm)

~/.virtualenvs/hype/lib/python3.6/site-packages/pywxclient/core/client.py in send_message(self, message)
    201 
    202         msg_ret = self.msg_send_routines[message.msg_type](
--> 203             self.session, message)
    204 
    205         local_msg_id = msg_ret['LocalID']

~/.virtualenvs/hype/lib/python3.6/site-packages/pywxclient/core/api.py in wrapper(cls, *args, **kwargs)
     36                     raise SessionExpiredError
     37 
---> 38                 raise APIResponseError
     39 
     40         return res

APIResponseError: 
```

I also run the [threaded example](https://github.com/justdoit0823/pywxclient/blob/master/examples/thread_client.py), same error there. I can receive and read the incoming messages with it, though.

**Comment by justdoit0823** [comment]
@nvilcins you should use the valid `UserName` in your contact list, which can be pulled with `client.get_contact` method. And the from_user must be your `UserName`, while to_user can be any other `UserName` in you wechat contact list.

**Comment by nvilcins** [comment]
Sorry for not being explicit about this.
`UserName` is exactly what I was using (the `@7af4725b8a...` type of string), just hid it in the snippet above for privacy.
Nonetheless, using the `thread_client.py` example I am not managing any logic, so the correct values must have been passed for sending messages. But the same error is thrown.
Am I missing any account-specific settings? I can use the macOS (official?) WeChat client just fine, so the account shouldn't be blocked or something..

**Comment by justdoit0823** [comment]
Yes, the `thread_client.py` program simulates a dialog as wechat app. When receiving messages, which are printed on the terminal, while you can reply messages with terminal input. In theory, you don't need any account-specific settings. As long as you can login successfully, your account is safe. According to you description, I can't get what happended. Can you provide more informations about your case? Such as system version, Python version, locale setting.

**Comment by wingjay** [comment]
Same error. My question is what `APIResponseError` means? like what type of error?

I can login successfully, I can invoke `client.get_contact()` function, while not `send_message()`. I have no idea about what happens under this error.

```
In [64]: client.send_message(textMsg)
---------------------------------------------------------------------------
APIResponseError                          Traceback (most recent call last)
<ipython-input-64-e49dc15a9025> in <module>()
----> 1 client.send_message(textMsg)

~/py3-venv/lib/python3.6/site-packages/pywxclient/core/client.py in send_message(self, message)
    208
    209         msg_ret = self.msg_send_routines[message.msg_type](
--> 210             self.session, message)
    211
    212         local_msg_id = msg_ret['LocalID']

~/py3-venv/lib/python3.6/site-packages/pywxclient/core/api.py in wrapper(cls, *args, **kwargs)
     36                     raise SessionExpiredError
     37
---> 38                 raise APIResponseError
     39
     40         return res

APIResponseError:
```

Thanks.

**Comment by wingjay** [comment]
I think i just figure it out.

All of `UserName` is changing once session expired. So we need update newest `UserName` value whenever we login.

**Comment by justdoit0823** [comment]
@wingjay Yes, you are right. For privacy, the `UserName` is just a key that dynamically maps to the real wechat account in your contact and only valid within a session. So when the session is expired, the `UserName` is useless. Also after a new successful login, you need to fetch the new `UserName` list and use them to send message.

Now, `APIResponseError` is a general exception represents requesting wechat HTTP api has failed without any detailed error message. Lack of wechat's open explaination, I can't give the real answer.

**Comment by nvilcins** [comment]
Yes indeed, the problem was the changing `UserName`. Have to refresh it for every session.
